version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting Docker Build"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 376129840486.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t my-docker-repo/mlproject .
      - docker tag my-docker-repo/mlproject:latest 376129840486.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest
  post_build:
    commands:
      - docker push 376129840486.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest

artifacts:
  files:
    - '**/*'